const moduloA = require('./moduloA')
const moduloB = require('./moduloB')
console.log("modulo a\n objeto exportado: ", moduloA)
console.log(moduloA.ateLogo)
console.log(moduloA.bemVindo)
console.log(moduloA.ola)
console.log("moduo b\n objeto exportado: ", moduloB)
console.log(moduloB.boaNoite())
console.log(moduloB.bomDia)
